[package]
name = "lngcnv"
version = "1.4.0-alpha"
authors = ["Piotr Bajdek <piotr.bajdek@protonmail.com>"]
edition = "2021"
description = "command line linguistic tools: display pronunciation, translate between dialects, convert between orthographies; support for multiple modern and ancient languages: English, Latin, Polish, Quechua, Tikuna"
documentation = "https://github.com/piotrbajdek/lngcnv/wiki"
readme = "README.md"
repository = "https://github.com/piotrbajdek/lngcnv"
license = "MIT"
keywords = ["linguistics", "phonetics", "pronunciation", "speech", "spelling"]
categories = ["command-line-utilities", "text-processing", "algorithms"]
